[package]
name = "user"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "user"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
user_integrity = { workspace = true }
